### ISSUE TITLE
Umbraco 13 System.TypeLoadException

### ISSUE THREAD

**Issue by slag-dev** [UmbHost/Our.Umbraco.Forms.uCaptcha#10]
uCaptcha 5.0.0 / Umbraco 13.2.2 / Umbraco Forms: 13.1.1 / Umbraco Cloud

When attempting to deploy new update on Umbraco Cloud we get following errors:
System.TypeLoadException: Could not load type 'Umbraco.Forms.Core.Attributes.Setting' from assembly 'Umbraco.Forms.Core, Version=13.0.2.0, Culture=neutral, PublicKeyToken=null'.

if we remove your package Umbraco Forms works as expected.

**Comment by AaronSadlerUK** [comment]
Hi @slag-dev 

I will investigate

**Comment by AaronSadlerUK** [comment]
@slag-dev I have taken a look and I can get this running on those versions...

Could you check to see if you have Umbraco.Forms.Core 13.0.2.0 referenced anywhere?
Maybe you need to explicitly install version 13.1.1?

**Comment by slag-dev** [comment]
Hi @AaronSadlerUK 

No we don't have any dependencies for Umbraco.Core 13.0.2.0 only 13.1.1... on the local environment it works but if we deploy it to the umbraco cloud the error occurs...

**Comment by AaronSadlerUK** [comment]
Hi @slag-dev 

Ok, we don't have a way of testing with Umbraco Cloud (due to our hosting products)
We have it working on our site, in local development and other non Umbraco Cloud V13 sites.

Could you reach out to Umbraco Cloud support

**Comment by slag-dev** [comment]
Hi @AaronSadlerUK 

Thanks for your feedback. Yes we contacted them but they said it's a third party package...

**Comment by AaronSadlerUK** [comment]
I would need access to a Umbraco Cloud project to be able to investigate

**Comment by slag-dev** [comment]
that could be a bit tricky :)

**Comment by AaronSadlerUK** [comment]
@slag-dev I managed to trigger this error on one of my upgrades, I was able to fix it by upgrading another package which was not updated to support V13.

In this case it was my Our.Umbraco.Forms.Intl_Tel_Input input package, so my advice would be to check all of your Umbraco Forms packages support Umbraco 13

**Comment by slag-dev** [comment]
@AaronSadlerUK thanks for your feedback - from my point of view all dependencies should be up to date and support umbraco v13. we don't have any other umbraco forms addons.

**Comment by AaronSadlerUK** [comment]
@slag-dev Ok, thee must be some other issue, we have upgraded our website to 13.2.2 (https://umbhost.net) and the plugin works correctly, we also spoke with another developer using V13 over the weekend and it works correctly for them.

The package does not have any dependencies on other Umbraco packages, I was explaining that the fix for ours was to update another unrelated package.

If you wish to investigate and submit a PR the source code is available, otherwise we can  investigate if you can provide access to the source code at our usually hourly rate.

**Comment by slag-dev** [comment]
perfect thanks for your offer - we will check everything again
