### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by creativesuspects** [UmbHost/Our.Umbraco.Forms.uCaptcha#4]
Would it be possible to remove the jQuery dependency? Umbraco Forms now uses the much smaller https://github.com/ryanelian/aspnet-validation library by default.

**Comment by AaronSadlerUK** [comment]
Sounds good, I'll investigate this 👍

**Comment by AaronSadlerUK** [comment]
@creativesuspects can you confirm you are using the latest V4?

https://www.nuget.org/packages/Our.Umbraco.Forms.uCaptcha/4.0.0-preview

I'm not able to find any jQuery in this version, please let me know if I looking in the wrong place though!

**Comment by creativesuspects** [comment]
My bad, I was using the latest 3.x release. I will upgrade to 4.0.0.
