### ISSUE TITLE
Unable to setup uCaptcha on frontend

### ISSUE THREAD

**Issue by aguyfromdenmark** [UmbHost/Our.Umbraco.Forms.uCaptcha#9]
I am unable to get uCaptcha to work on the frontend. 
I am already using Umbraco Forms without problems, and I have followed the setup guide, and the required theme changes. 
Still, it seems like uCaptcha is expecting something to be there, that is not there:
![image](https://github.com/UmbHost/Our.Umbraco.Forms.uCaptcha/assets/6904597/42564cda-127b-4d91-9562-75c3752bf75c)

We are using a custom theme, in the way that we are using a custom `Form.cshtml` file, but relying on the default theme for anything else. So I added the default theme as mentioned in the required theme changes, and reinstalled uCaptcha. That did nothing. 

![image](https://github.com/UmbHost/Our.Umbraco.Forms.uCaptcha/assets/6904597/06a686ba-7b8a-4ef4-a75a-eb90726172ed)

Am i misunderstanding something, or is this broken?

**Comment by AaronSadlerUK** [comment]
Hi @aguyfromdenmark 

It looks like the file copy is now working, can you manually create this file:

https://github.com/UmbHost/Our.Umbraco.Forms.uCaptcha/blob/main/src/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.uCaptcha.cshtml

**Comment by aguyfromdenmark** [comment]
Thanks @AaronSadlerUK , that did the trick :)
